name: Build Windows Super
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'master'
    tags:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 480
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      MODE: release
      TARGET_OS: win
      TARGET_ARCH: ${{ matrix.arch }}
      BRANDING: ${{ matrix.branding }}
      JOBS: 4
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        arch: [x64]
        branding: [supermind]
    steps:

    # Checkout
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_GITHUB_ACTIONS }}
        lfs: false

    # Load Dependencies from Cache
    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: |
          deps/build/make/bin/win-*
          deps/build/make/lib/win-*
        key: dependencies-${{ env.BRANCH_NAME }}-${{ env.TARGET_OS }}-${{ env.TARGET_ARCH }}-${{ matrix.os }}-${{ hashFiles('deps/VERSION') }}

    # Developer Console (X64)
    - name: MSVC Developer Console (X64)
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    # Build QtTools (X64)
    - name: Build QtTools (X64)
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: make TARGET_ARCH=x64 QtTools -j${{ env.JOBS }}

    # Developer Console (X86)
    - name: MSVC Developer Console (X86)
      if: matrix.arch == 'x86'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86

    # Developer Console (ARM64)
    - name: MSVC Developer Console (ARM64)
      if: matrix.arch == 'arm64'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_arm64

    # Build Dependencies
    - name: Build Dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: make Dependencies -j${{ env.JOBS }}

    # Build Engine
    - name: Build Engine
      run: make Engine -j${{ env.JOBS }}

    # Build QtBase
    - name: Build QtBase
      run: make QtBase -j${{ env.JOBS }}

    # Build Studio
    - name: Build Studio
      run: make Studio -j${{ env.JOBS }}

    # Build EngineLIB
    - name: Build EngineLIB
      run: make EngineLIB -j${{ env.JOBS }}

    # Build EngineJNI
    - name: Build EngineJNI
      run: make EngineJNI -j${{ env.JOBS }}

    # Binary Info
    - name: Binary Info
      run: |
        dumpbin /dependents /exports ./build/make/bin/win-${{ env.TARGET_ARCH }}/Studio.exe
        dumpbin /dependents /exports ./build/make/lib/win-${{ env.TARGET_ARCH }}/EngineLIB.dll
        dumpbin /dependents /exports ./build/make/lib/win-${{ env.TARGET_ARCH }}/EngineJNI.dll

    # PDB Info
    - name: PDB Info
      run: llvm-pdbutil dump --summary ./build/make/bin/win-${{ env.TARGET_ARCH }}/Studio.pdb

    # Upload Studio
    - name: Upload Studio
      uses: actions/upload-artifact@v4
      with:
        name: Binaries (${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.branding }})
        path: |
          ./build/make/bin/win-${{ matrix.arch }}/*.exe
          ./build/make/bin/win-${{ matrix.arch }}/*.dll
          ./build/make/bin/win-${{ matrix.arch }}/*.pdb

    # Upload Engine
    - name: Upload Engine
      uses: actions/upload-artifact@v4
      with:
        name: Engine (${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.branding }})
        path: |
          ./src/Engine/neuromoreEngine.h
          ./build/make/lib/win-${{ matrix.arch }}/EngineLIB.dll
          ./build/make/lib/win-${{ matrix.arch }}/EngineLIB.lib
          ./build/make/lib/win-${{ matrix.arch }}/EngineLIB.pdb
          ./build/make/lib/win-${{ matrix.arch }}/EngineJNI.dll
          ./build/make/lib/win-${{ matrix.arch }}/EngineJNI.pdb
          ./build/make/lib/win-${{ matrix.arch }}/EngineJNI.jar
